name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 8 * * *'

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4  # Updated to v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest playwright allure-pytest
        playwright install
        playwright install-deps
        # Install Allure commandline
        sudo apt-get update -y
        sudo apt-get install default-jre -y
        wget -qO- https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz | tar -xz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        echo "/opt/allure/bin" >> $GITHUB_PATH
    
    - name: Run Playwright tests with Allure
      run: |
        python -m pytest tests/ -v --alluredir=allure-results
    
    - name: Generate Allure report
      run: |
        allure generate allure-results --clean -o allure-report
    
    - name: Upload Allure report
      uses: actions/upload-artifact@v4  # Updated to v4
      with:
        name: allure-report
        path: allure-report
    
    # Optional: Comment with report link on PR
    - name: Add PR comment with report link
      if: github.event_name == 'pull_request'
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `📊 Allure report available [here](https://github.com/${context.repo.owner}/${context.repo.repo}/actions/runs/${context.runId}#artifacts)`
          })